baseURL = "mcg.sh"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "mcg.sh < MCG | blog"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-1229396-9"
disqusShortname = "mcg-sh"
enableGitInfo = true

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "Blog by mcg<br/>(aka Marcelo Gonçalves)"
  homeMetaContent = "Blog by mcg (aka Marcelo Gonçalves) about programming, software architecture and game development."
  footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/)."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = "marcelocg"
  katex = true

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
