[build]
  HUGO_VERSION = "0.55.6"
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[build.environment]
  HUGO_VERSION = "0.55.6"
